"""Initial migration

Revision ID: 499724a0b9a8
Revises: 
Create Date: 2025-07-09 12:28:27.691628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499724a0b9a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('role', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('content', sa.String(), nullable=False))
    op.alter_column('chat_messages', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['chat_id'], ['session_id'])
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.alter_column('chat_messages', 'chat_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chat_messages', 'content')
    op.drop_column('chat_messages', 'role')
    # ### end Alembic commands ###
